// ═══════════════════════════════════════════════════════════════════════════
// Automated Fix Queries — Generated by Ontology Validator
// Generated: 2026-02-24T19:38:22.447Z
// ═══════════════════════════════════════════════════════════════════════════

// ─── SAFE FIXES (review queries, no data modification) ──────────────────

// Review instance counts per class label
// Violation: 8 ontology class(es) have no instances in the graph: Non-InformationResource, EuropeanaAggregation, EuropeanaObject, Aggregation, Event, InformationResource, PhysicalThing, Proxy
CALL db.labels() YIELD label MATCH (n) WHERE label IN labels(n) RETURN label, count(n) AS count ORDER BY count DESC

// List all property keys for manual review
// Violation: 21 property key(s) not explicitly defined in the ontology.
CALL db.propertyKeys() YIELD propertyKey RETURN propertyKey ORDER BY propertyKey
