// ═══════════════════════════════════════════════════════════════════════════
// Automated Fix Queries — Generated by Ontology Validator
// Generated: 2026-02-24T12:45:13.242Z
// ═══════════════════════════════════════════════════════════════════════════

// ─── SAFE FIXES (review queries, no data modification) ──────────────────

// Review nodes with "hasURL" outside domain
// Violation: Data property "hasURL" found on nodes outside its domain. Expected domain: [Endeavour].
MATCH (n) WHERE n.`hasURL` IS NOT NULL AND NOT any(l IN labels(n) WHERE l IN ['Endeavour']) RETURN n.id, labels(n), n.`hasURL` LIMIT 20

// Review nodes with "issueIdentifier" outside domain
// Violation: Data property "issueIdentifier" found on nodes outside its domain. Expected domain: [Endeavour].
MATCH (n) WHERE n.`issueIdentifier` IS NOT NULL AND NOT any(l IN labels(n) WHERE l IN ['Endeavour']) RETURN n.id, labels(n), n.`issueIdentifier` LIMIT 20

// Review nodes with "hasSequenceIdentifier" outside domain
// Violation: Data property "hasSequenceIdentifier" found on nodes outside its domain. Expected domain: [Endeavour].
MATCH (n) WHERE n.`hasSequenceIdentifier` IS NOT NULL AND NOT any(l IN labels(n) WHERE l IN ['Endeavour']) RETURN n.id, labels(n), n.`hasSequenceIdentifier` LIMIT 20

// Review nodes with "publicationDate" outside domain
// Violation: Data property "publicationDate" found on nodes outside its domain. Expected domain: [Endeavour].
MATCH (n) WHERE n.`publicationDate` IS NOT NULL AND NOT any(l IN labels(n) WHERE l IN ['Endeavour']) RETURN n.id, labels(n), n.`publicationDate` LIMIT 20

// Review nodes with "isbn" outside domain
// Violation: Data property "isbn" found on nodes outside its domain. Expected domain: [Endeavour].
MATCH (n) WHERE n.`isbn` IS NOT NULL AND NOT any(l IN labels(n) WHERE l IN ['Endeavour']) RETURN n.id, labels(n), n.`isbn` LIMIT 20

// Review nodes with "volume" outside domain
// Violation: Data property "volume" found on nodes outside its domain. Expected domain: [Endeavour].
MATCH (n) WHERE n.`volume` IS NOT NULL AND NOT any(l IN labels(n) WHERE l IN ['Endeavour']) RETURN n.id, labels(n), n.`volume` LIMIT 20

// Review nodes with "pageRange" outside domain
// Violation: Data property "pageRange" found on nodes outside its domain. Expected domain: [Endeavour].
MATCH (n) WHERE n.`pageRange` IS NOT NULL AND NOT any(l IN labels(n) WHERE l IN ['Endeavour']) RETURN n.id, labels(n), n.`pageRange` LIMIT 20

// Review orphaned nodes by label
// Violation: 8,140 orphaned node(s) (0.05% of graph) have no relationships.
MATCH (n) WHERE NOT (n)--() RETURN labels(n) AS labels, count(*) AS count ORDER BY count DESC

// ─── MODERATE FIXES (data modification, reversible) ──────────────────────

// Remove invalid label "Person" from all nodes
// Violation: Label "Person" is not defined in the ontology. Found 4,097,863 nodes with this label.
// Risk: MODERATE — Review before executing
MATCH (n:`Person`) REMOVE n:`Person`

// Remove invalid label "Organization" from all nodes
// Violation: Label "Organization" is not defined in the ontology. Found 2,343 nodes with this label.
// Risk: MODERATE — Review before executing
MATCH (n:`Organization`) REMOVE n:`Organization`

// ─── DESTRUCTIVE FIXES (data deletion, NOT reversible) ───────────────────
// WARNING: These queries DELETE data. Review carefully before uncommenting.

// Delete all orphaned nodes (DESTRUCTIVE)
// Violation: 8,140 orphaned node(s) (0.05% of graph) have no relationships.
// Risk: DESTRUCTIVE — Data will be permanently deleted
// DESTRUCTIVE: Uncomment to delete orphaned nodes
// MATCH (n) WHERE NOT (n)--() DELETE n
